version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: centro_down_db
      MYSQL_USER: centro_down
      MYSQL_PASSWORD: admin1234
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306