version: '3.8'


services:

   mongo-db:
     image: mongo:6.0.6
     restart: always
     environment:
       MONGO_INITDB_ROOT_USERNAME: centro-down
       MONGO_INITDB_ROOT_PASSWORD: admin1234
     volumes:
       - ./mongo:/data/db
     ports:
       - 27017:27017